### ISSUE TITLE
怎样获取到代理池的端口有哪些呢？

### ISSUE THREAD

**Issue by tp-life** [iotames/v2raypool#1]
如题

**Comment by iotames** [comment]
项目主页有写：[README.md](https://github.com/iotames/v2raypool/blob/master/README.md)

就在使用说明的第5步。先运行服务端，再运行客户端命令 `v2raypool.exe --getproxynodes` 去查询。

### 5. 运行服务端和客户端

5.1 服务端

可执行文件直接运行，启动 `gRPC` 服务端

```
# linux 或 mac 执行 ./v2raypool
v2raypool.exe
```

5.2 客户端

`gRPC` 客户端交互命令:

```
# 启动v2ray代理池
v2raypool.exe --startproxynodes

# 查看v2ray代理池信息(包括：本地代理端口号，测速结果，运行状态，测速时间，节点名，节点索引)
v2raypool.exe --getproxynodes

# 测速(测速基准使用https://www.google.com)。测速结束后，会自动选择最快的节点作为系统代理节点。
v2raypool.exe --testproxynodes

# 根据索引值激活某个节点为系统代理的端口（--getproxynodes 查看索引值，系统代理端口从VP_HTTP_PROXY的值读取）
v2raypool.exe --activeproxynode=16

# 停止所有节点
v2raypool.exe --stopproxynodes
```

**Comment by tp-life** [comment]
感谢，实际运行中报错： ---ParseV2rayNodes--Base64.Decode--err(illegal base64 data at input byte 64)---RAW(ss://YWVzLTE345yOC1nYxxxx206MzNiNWEyZWMtMmU3Mi00Zm2mUzLTg1OTItZDZhMzA4N2RmNDg3@example.xxx.com:12051#%F0%9F%87%B0%F0%9F%87%B)---%E9%9F%A9%E5%9B%BD%20%E4%B8%93%E7%BA%BF%20E1。 看样子是对订阅地址返回的数据解析失败了。请问对于解析的数据格式是什么样子的？上面的代理信息已经做过处理了，可以支持这种格式吗？

**Comment by iotames** [comment]
## 节点订阅源解析步骤

1. 从订阅源的URL网址获取Base64加密过的字符串，里面包含所有代理节点的信息。
2. 解析Base64字符串，得到以 `\n` 换行符分割的多个代理节点信息。每个节点信息也是被Base64加密过的。格式为: `协议://Base64加密字符串`。如: `ss://xxxxxxxxxxxxxxx` 或 `vmess://XXXXXXXXXXXX==`。 非法格式为: `ss://YWVzLTEXXXNDg3@example.xxx.com`
3. 解密Base64加密过的节点。如果解密失败，则该节点会被忽略，提示: `---ParseV2rayNodes--Base64.Decode--err`，然后继续解密下个节点。
4. 如果Base64解密成功，则结果为json字符串。再继续解析该json字符串信息。合法的json信息示例: `{"add":"addr1.xxxxx.com","host":"","id":"93XXXXXX-EA21-7240-EE7F-317FXXXXXXXX","net":"ws","path":"","port":"444","ps":"xxxx-v2-HK-XXXXXX1","tls":"tls","type":"none","v":2,"aid":0}`
若解析错误则会提示: `-ParseV2rayNodes--json.Unmarshal err--`，然后继续下一个节点。


## 调试工具

- base64在线解析网站: [https://base64.us/](https://base64.us/)
