### ISSUE TITLE
几个使用上的问题

### ISSUE THREAD

**Issue by nizhenyu2022** [iotames/v2raypool#10]
1，如果订阅源是txt
比如
http://127.0.0.1/socks5.txt
内容为
socks5://8.8.8.8:1080
socks5://9.9.9.9:1080
这样是否能做到。
2，会考虑多个订阅源吗？
3，会考虑加入http以及https代理作为池子节点吗
感谢开发者开发出这么好的软件。

**Comment by iotames** [comment]
1和3的使用场景是什么？

**Comment by nizhenyu2022** [comment]
> 1和3的使用场景是什么？

1,3的使用场景就是github上很多分享的https代理，例如
https://raw.githubusercontent.com/SevenworksDev/proxy-list/main/proxies/https.txt
https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/https.txt
这些都是实时更新的，比较短效，如果存到本地再用BASE64加密，使用效果大打折扣，所以希望能多个订阅源定时实时抓取，检测存活。

**Comment by iotames** [comment]
因为网上很多免费的代理池太短效，基本用不了，才开发这个小项目。
对代理池要求高的，使用付费的代理池好些。不建议用免费的。

确实有此类需求的，不少专门做IP代理池的项目，已经很成熟，可以满足。
缺点是没法用v2ray订阅源节点，毕竟用途不一样。

| 项目      | Docker支持 | 数据库  | 作者 | 链接地址                                  |
| ----------- | ---------- | ---------- | ------ | --------------------------------------------- |
| proxy_pool  | 是        | Redis,SSDB |        | https://github.com/jhao104/proxy_pool         |
| ProxyPool   | 是        | Redis      | 崔庆才 | https://github.com/Python3WebSpider/ProxyPool |
| haipproxy   | 是        | Redis      |        | https://github.com/SpiderClub/haipproxy       |
| IPProxyTool | 是        | mysql      |        | https://github.com/awolfly9/IPProxyTool       |
