### ISSUE TITLE
测速(www.google.com)正常，代理使用不了，大佬帮忙看看如何解决

### ISSUE THREAD

**Issue by ZeaoYang** [iotames/v2raypool#11]
测速(www.google.com)正常，代理使用不了，大佬帮忙看看如何解决
![屏幕截图 2024-04-23 153937](https://github.com/iotames/v2raypool/assets/59384506/8c512dd1-9b5f-4400-a32b-d516014b76a5)

**Comment by iotames** [comment]
> 测速([www.google.com)正常，代理使用不了，大佬帮忙看看如何解决](http://www.google.com)%E6%AD%A3%E5%B8%B8%EF%BC%8C%E4%BB%A3%E7%90%86%E4%BD%BF%E7%94%A8%E4%B8%8D%E4%BA%86%EF%BC%8C%E5%A4%A7%E4%BD%AC%E5%B8%AE%E5%BF%99%E7%9C%8B%E7%9C%8B%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3) ![屏幕截图 2024-04-23 153937](https://private-user-images.githubusercontent.com/59384506/324740112-8c512dd1-9b5f-4400-a32b-d516014b76a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjUwMDgsIm5iZiI6MTcxMzg2NDcwOCwicGF0aCI6Ii81OTM4NDUwNi8zMjQ3NDAxMTItOGM1MTJkZDEtOWI1Zi00NDAwLWEzMmItZDUxNjAxNGI3NmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NDcxZmNmODJkYjVmMzRkYzlkZTEwMmZmMDA0YzlhMmYyMmQ0NGQxMjc2YWQzMjIyYzdlODViZDJkMDAwY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._1VWwWShJSkCllLML2wWtJ92wSOxf7V2EG9DQugRE7Q)

测速不正常。都是红的。绿的才是正常的！
是不是订阅源过期忘记续费了？😁
