### ISSUE TITLE
考虑一下支持 trojan 吧 

### ISSUE THREAD

**Issue by Smart-Yi** [iotames/v2raypool#12]
机场只有  trojan  和 vless 结果都不支持

**Comment by iotames** [comment]
trojan协议的单节点已测试通过，无奈手头暂时没有trojan订阅源，没有订阅的原始数据格式，无法调试解析流程。

不知道你的订阅源数据是 `base64编码的字符串` 还是clash使用的那种 `yml文件` 。

现已支持的 `vmess://` 和 `ss://` ，数据都是  `base64编码的字符串`  😆

**Comment by Smart-Yi** [comment]
其实不需要在意订阅的格式问题，现在机场都是根据使用的软件来分别提供订阅地址。你使用clash你就复制clash的订阅地址，你使用v2ray你就复制v2ray的订阅地址，所以没必要纠结和支持yml，用户会自己选择的

**Comment by Smart-Yi** [comment]
github上免费的机场一大把.
我这里也有trojan的节点，你要用的话可以提供给你，我这里只有trojan和vless，现在ss 也用的少了

**Comment by iotames** [comment]
已支持。请升级到最新版本。若节点解析错误请反馈。

**Comment by Smart-Yi** [comment]
:)
