### ISSUE TITLE
删除选定的代理

### ISSUE THREAD

**Issue by expiren** [iotames/v2raypool#15]
有些代理无法正常运行，因此我们需要将其删除。最简单的方法是从用户界面 (UI) 中选择并删除它们。这是一个前端修改，比删除所有代理、删除损坏的代理和修改整个“subscribe_data.txt”要好。

最后，我们应该跳过任何死的或损坏的代理，因为它们可能会导致整个脚本停止并导致错误。

"("500错误
rpc error: code = Unknown desc = app/proxyman/inbound: failed to listen TCP on 30001 > transport/internet: failed to listen on address: 0.0.0.0:30001 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:30001 > listen tcp 0.0.0.0:30001: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.")"

**Comment by iotames** [comment]
远程代理节点无法工作，要测速后才能知晓。若节点不可用，不会导致整个脚本停止。
你这个报错，是启动所有节点时，因为本地端口号被占用，导致一个入站端口启动失败。不是出站的远程代理节点问题。

**Comment by expiren** [comment]
您说得对，但问题只发生在一个特定的本地端口。经过进一步调查，显然本地端口被占用，因为应用程序在运行时选择其中一个节点并成为系统代理。当尝试使用同一端口运行同一节点时，会出现此问题，因为该端口已被应用程序使用。因此，解决此问题的方法在于选择手动或自动控制是否可以将节点设置为系统代理。
谢谢。
