### ISSUE TITLE
ss节点导入不显示或者没有用

### ISSUE THREAD

**Issue by Passerby1011** [iotames/v2raypool#17]
如题，节点信息一起以base64的的格式写在配置里，其中trojan节点正常导入了，所有的ss节点全部没有显示（节点信息是一起从v2rayN中导出的），作者如果有测试的需要可以联系我提供节点信息

**Comment by iotames** [comment]
提供 `base64解码` 之后， `ss://` 开头的几行数据的样例就行。不需要填真实信息。敏感部分用1234或abcd代替。如下所示：

```
ss://xxxxxxxxxx@ru1.abcd.com:1234/?plugin=v2ray-plugin%3bmode%3dwebsocket%3bpath%3d%2f%3bmux%3dtrue%3b#abcd-RU-Ru1
```

**Comment by Passerby1011** [comment]
ss://xxxxxxxxxxxxxxxxxxxxxx@usus.cdn.lifhgsgadjsad.xyz:47545#%F0%9F%87%BA%F0%9F%87%B8%20United%20States01

**Comment by iotames** [comment]
v1.6.4版本更新了解析规则
