### ISSUE TITLE
---ParseV2rayNodesErr--(0)--err(parseNodeInfo err(json: cannot unmarshal number into Go struct field V2rayNode.Port

### ISSUE THREAD

**Issue by koushui** [iotames/v2raypool#6]
I use subscribe_data.txt, the subscription address inside is the address in the format provided by your "README":

vmess://eyJhZGQiOiAiMjAyLjc4LjE2Mi41IiwgImFpZCI6IDAsICJob3N0IjogImlyc29mdC5zeXRlcy5uZXQiLCAiaWQiOiAiMmZmOTdjNmQtODU1Ny00MmE0LWI0M2YtMTljNzdjNTk1OWV hIiwgIm5ldCI6ICJ3cyIsICJwYXRoIjogIi9AZm9yd2FyZHYycmF5IiwgInBvcnQiOiA0NDMsICJwcyI6ICJnaXRodWIuY29tL2ZyZWVmcSAtIFx1NTM3MFx1NWVhNiAgMiIsICJ0bHMiOiAidGxzIi wgInR5cGUiOiAiYXV0byIsICJzZWN1cml0eSI6ICJhdXRvIiwgInNraXAtY2VydC12ZXJpZnkiOiB0cnVlLCAic25pIjogIiJ9
vless://26DL68CE-DL93-8342-LQ8F-317F4A6E7J76@45.43.31.159:443?encryption=none&security=reality&sni=azure.microsoft.com&fp=safari&pbk=c7qU9-_0WflwIKUiZFxSss_xw-2AP3jB1ENxKLI0OT w&type=tcp&headerType=none#u9un-US-Xr1
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTozNlpDSGVhYlVTZktqZlFFdko0SERW@185.242.86.156:54170#github.com/freefq%20-%20%E4%BF%84%E7%BD%97%E6%96%AF%20%201
ss://YWVzLTI1Ni1nY206N0JjTGRzTzFXd2VvR0QwWA@193.243.147.128:40368#github.com/freefq%20-%20%E6%B3%A2%E5%85%B0%20%205
vmess://eyJhZGQiOiAic2VydmVyMzEuYmVoZXNodGJhbmVoLmNvbSIsICJhaWQiOiAwLCAiaG9zdCI6ICJzZXJ2ZXIzMS5iZWhlc2h0YmFuZWguY29tIiwgImlkIjogIjQxNTQxNDNjLWJiYmEt NDdhNC05Zjc5LWMyZWQwODdjYmNjOSIsICJuZXQiOiAid3MiLCAicGF0aCI6ICIvIiwgInBvcnQiOiA4ODgwLCAicHMiOiAiZ2l0aHViLmNvbS9mcmVlZnEgLSBcdTdmOGVcdTU2ZmRDbG91ZEZsYXJ lXHU1MTZjXHU1M2Y4Q0ROXHU4MjgyXHU3MGI5IDYiLCAidGxzIjogIiIsICJ0eXBlIjogImF1dG8iLCAic2VjdXJpdHkiOiAiYXV0byIsICJza2lwLWNlcnQtdmVyaWZ5IjogdHJ1ZSwgInNuaSI6ICIifQ ==

Then perform base64 results at https://base64.us/. The v2ray-core used is the latest version v5.15.1, but the error is reported as follows：

v2raypool.exe
------LoadEnv--env-files([.env default.env])
---Begin---parseSubscribeByRaw---
-----Begin--ParseV2rayNodes-------

---ParseV2rayNodesErr--(0)--err(parseNodeInfo err(json: cannot unmarshal number into Go struct field V2rayNode.Port of type string) for vmess json Unmarshal({"add": "202.78.162.5", "aid": 0, "host": "irsoft.sytes.net", "id": "2ff97c6d-8557-42a4-b43f-19c77c5959ea", "net": "ws", "path": "/@forwardv2ray", "port": 443, "ps": "github.com/freefq - \u5370\u5ea6  2", "tls": "tls", "type": "auto", "security": "auto", "skip-cert-verify": true, "sni": ""}))---RAW(vmess://eyJhZGQiOiAiMjAyLjc4LjE2Mi41IiwgImFpZCI6IDAsICJob3N0IjogImlyc29mdC5zeXRlcy5uZXQiLCAiaWQiOiAiMmZmOTdjNmQtODU1Ny00MmE0LWI0M2YtMTljNzdjNTk1OWVhIiwgIm5ldCI6ICJ3cyIsICJwYXRoIjogIi9AZm9yd2FyZHYycmF5IiwgInBvcnQiOiA0NDMsICJwcyI6ICJnaXRodWIuY29tL2ZyZWVmcSAtIFx1NTM3MFx1NWVhNiAgMiIsICJ0bHMiOiAidGxzIiwgInR5cGUiOiAiYXV0byIsICJzZWN1cml0eSI6ICJhdXRvIiwgInNraXAtY2VydC12ZXJpZnkiOiB0cnVlLCAic25pIjogIiJ9)

---ParseV2rayNodesErr--(1)--err(protocol not support vless)---RAW(vless://26DL68CE-DL93-8342-LQ8F-317F4A6E7J76@45.43.31.159:443?encryption=none&security=reality&sni=azure.microsoft.com&fp=safari&pbk=c7qU9-_0WflwIKUiZFxSss_xw-2AP3jB1ENxKLI0OTw&type=tcp&headerType=none#u9un-US-Xr1)

---ParseV2rayNodesErr--(2)--err(protocol not support ss)---RAW(ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTozNlpDSGVhYlVTZktqZlFFdko0SERW@185.242.86.156:54170#github.com/freefq%20-%20%E4%BF%84%E7%BD%97%E6%96%AF%20%201)

---ParseV2rayNodesErr--(3)--err(protocol not support ss)---RAW(ss://YWVzLTI1Ni1nY206N0JjTGRzTzFXd2VvR0QwWA@193.243.147.128:40368#github.com/freefq%20-%20%E6%B3%A2%E5%85%B0%20%205)

Please check the reason.

**Comment by iotames** [comment]
only support vmess protocol.

the error report that:
```
 json: cannot unmarshal number into Go struct field V2rayNode.Port of type string
```
because the format of subscription address parse error.

your data:
```
{"add": "202.78.162.5", "aid": 0, "host": "irsoft.sytes.net", "id": "2ff97c6d-8557-42a4-b43f-19c77c5959ea", "net": "ws", "path": "/@FORWARDV2RAY", "port": 443, "ps": "github.com/freefq - \u5370\u5ea6 2", "tls": "tls", "type": "auto", "security": "auto", "skip-cert-verify": true, "sni": ""}
```

expected data:
```
{"add":"us0.uxxx.top","host":"","id":"xxxx-7240-EE7F-317xxxx","net":"ws","path":"","port":"444","ps":"u9un-v2-US-LosAngeles0","tls":"","type":"none","v":2,"aid":0}
```

**This BUG will be Fixed soon!**

**Comment by koushui** [comment]
Will you consider supporting more protocols, such as ss, trojan, socks5, etc.? It would be a pity if it is not supported

**Comment by iotames** [comment]
Considering support ss:// and trojan://
