### ISSUE TITLE
能支持开socks端口用吗？

### ISSUE THREAD

**Issue by nizhenyu2022** [iotames/v2raypool#7]
不胜感激

**Comment by iotames** [comment]
入站的socks还是出站的socks？
是要把入站代理地址 `http://127.0.0.1:30000` 改成 `socks://127.0.0.1:30000` 使用？

**Comment by nizhenyu2022** [comment]
对，改成 socks://127.0.0.1:30000 使用，可以这样吗

**Comment by iotames** [comment]
v1.4.0已支持。在 `.env` 配置文件设置代理即可: `VP_HTTP_PROXY="socks5://127.0.0.1:30000"`
